const cfg = await fetch('/api/config').then(r=>r.ok?r.json():{}).catch(()=>({}));
const url = cfg.supabaseUrl; const anon = cfg.supabaseAnonKey;
const login = document.querySelector('#login'), dashboard = document.querySelector('#dashboard');
let token = localStorage.getItem('dd_staff_token'); let allOrders=[];
function msg(s){document.querySelector('#message').textContent=s}
async function auth(path, body){const r=await fetch(`${url}/auth/v1/${path}`,{method:'POST',headers:{'Content-Type':'application/json',apikey:anon},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.msg||d.message||'Sign in failed');return d}
async function load(){if(!url||!anon){msg('Dashboard configuration is missing.');return}if(!token){login.classList.remove('hidden');dashboard.classList.add('hidden');return}login.classList.add('hidden');dashboard.classList.remove('hidden');const r=await fetch(`${url}/rest/v1/orders?select=*&order=created_at.desc`,{headers:{apikey:anon,Authorization:`Bearer ${token}`}});if(r.status===401||r.status===403){localStorage.removeItem('dd_staff_token');token=null;return load()}if(!r.ok){msg('Could not load orders. Check staff access and database policies.');return}allOrders=await r.json();render()}
function render(){const q=document.querySelector('#search').value.toLowerCase();const status=document.querySelector('#status-filter').value;const rows=allOrders.filter(o=>(!status||o.order_status===status)&&JSON.stringify(o).toLowerCase().includes(q));const pending=allOrders.filter(o=>o.tracking_followup_status==='pending'&&new Date(o.tracking_followup_due_at)<=new Date()).length;document.querySelector('#stats').innerHTML=`<div class="stat"><strong>${allOrders.length}</strong>Total orders</div><div class="stat"><strong>${allOrders.filter(o=>o.payment_status==='paid').length}</strong>Paid</div><div class="stat"><strong>${pending}</strong>Tracking follow-ups</div>`;document.querySelector('#orders').innerHTML=rows.map(o=>`<tr><td>${new Date(o.created_at).toLocaleString()}</td><td>${esc(o.recipient_name||'')}<br>${esc(o.phone)}<br>${esc(o.dorm)} ${esc(o.room)}</td><td>${esc(o.service)} · ${o.quantity}${o.promo_code?`<br>${esc(o.promo_code)}`:''}<br><small>${esc(o.carrier||'Awaiting tracking')} ${esc(o.tracking||'')}</small></td><td>$${Number(o.amount_due).toFixed(2)}</td><td><select data-id="${o.id}" data-field="payment_status">${['unconfirmed','paid','refunded'].map(s=>`<option ${o.payment_status===s?'selected':''}>${s}</option>`)}</select></td><td><select data-id="${o.id}" data-field="order_status">${['payment_started','received','in_progress','completed','cancelled'].map(s=>`<option ${o.order_status===s?'selected':''}>${s}</option>`)}</select></td><td>${o.tracking_followup_status==='pending'&&new Date(o.tracking_followup_due_at)<=new Date()?`<a data-followup="${o.id}" href="sms:${encodeURIComponent(o.phone)}?body=${encodeURIComponent(`Hi${o.recipient_name?' '+o.recipient_name:''}, this is DukeDrop following up on your ${o.service} order. Could you send us the tracking number when available? We are following up 24 hours after your order.`)}">Text follow-up</a>`:esc(o.tracking_followup_status==='pending'?'Due '+new Date(o.tracking_followup_due_at).toLocaleDateString():o.tracking_followup_status||'Not needed')}</td></tr>`).join('');msg(rows.length?`${rows.length} orders shown.`:'No matching orders.')}
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
document.querySelector('#sign-in').onclick=async()=>{try{const d=await auth('token?grant_type=password',{email:document.querySelector('#email').value,password:document.querySelector('#password').value});token=d.access_token;localStorage.setItem('dd_staff_token',token);await load()}catch(e){document.querySelector('#login-message').textContent=e.message}};
document.querySelector('#sign-out').onclick=()=>{localStorage.removeItem('dd_staff_token');token=null;load()};document.querySelector('#refresh').onclick=load;document.querySelector('#search').oninput=render;document.querySelector('#status-filter').onchange=render;
document.querySelector('#orders').onchange=async e=>{const el=e.target;if(!el.dataset.id)return;const r=await fetch(`${url}/rest/v1/orders?id=eq.${el.dataset.id}`,{method:'PATCH',headers:{apikey:anon,Authorization:`Bearer ${token}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({[el.dataset.field]:el.value})});if(!r.ok)msg('Status update failed; verify update policy.');else{const o=allOrders.find(x=>x.id===el.dataset.id);o[el.dataset.field]=el.value;render()}};
document.querySelector('#orders').onclick=async e=>{const a=e.target.closest('[data-followup]');if(!a)return;e.preventDefault();const o=allOrders.find(x=>x.id===a.dataset.followup);const r=await fetch(`${url}/rest/v1/orders?id=eq.${o.id}`,{method:'PATCH',headers:{apikey:anon,Authorization:`Bearer ${token}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({tracking_followup_status:'sent',tracking_followup_sent_at:new Date().toISOString()})});if(!r.ok){msg('Could not mark follow-up as sent.');return}o.tracking_followup_status='sent';window.location.href=a.href;render()};
await load();
